# Generated by Django 5.1 on 2024-09-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Provider'), (2, 'Customer'), (3, 'Employee')], default=1),
        ),
    ]
